///////////////////////////////////////////////////////////////////
// Name:        html_css.cpp
// Purpose:     Standard CSS to be applied to elements.
// Copyright:   David Reynolds
// License:     Sower Applications License
///////////////////////////////////////////////////////////////////

#include "../../include/html/html_css.h"
#include "../../include/thml/thml_elements.h"

struct HTML_CSS_ELEMENT_CONST
{
    swUI16 m_element;
    const char * m_attribute1;
    const char * m_value1;
    const char * m_attribute2;
    const char * m_value2;
    const char * m_attribute3;
    const char * m_value3;
};

// This array must have all of the elements in ThMLElements
// array, and be in the precise order or it will not provide
// the correct style data.
static HTML_CSS_ELEMENT_CONST htmlCss [N_THML_ELEMENTS] =
{
    {THML_COMMENT, "", "", "", "", "", ""},
    {THML_DOCTYPE, "", "", "", "", "", ""},
    {THML_A, "text-decoration", "underline", "color", "blue", "", ""},
    {THML_ABBR,  "", "", "", "", "", ""},
    {THML_ACRONYM, "", "", "", "", "", ""},
    {THML_ADDED, "", "", "", "", "", ""},
    {THML_ADDRESS, "font-style", "italic", "", "", "", ""},
    {THML_APPLET, "", "", "", "", "", ""},
    {THML_AREA, "", "", "", "", "", ""},
    {THML_ARGUMENT, "", "", "", "", "", ""},
    {THML_ARTICLE, "", "", "", "", "", ""},
    {THML_ASIDE, "", "", "", "", "", ""},
    {THML_ATTLIST, "", "", "", "", "", ""},
    {THML_ATTR, "", "", "", "", "", ""},
    {THML_AUDIO, "", "", "", "", "", ""},
    {THML_AUTHOR, "", "", "", "", "", ""},
    {THML_AUTHORID, "", "", "", "", "", ""},
    {THML_AUTODEF_BODY, "font-family", "Times", "", "", "", ""},
    {THML_B, "font-weight", "bolder", "", "", "", ""},
    {THML_BASE, "", "", "", "", "", ""},
    {THML_BASEFONT, "", "", "", "", "", ""},
    {THML_BDI, "", "", "", "", "", ""},
    {THML_BDO, "", "", "", "", "", ""},
    {THML_BIG, "font-size", "1.31em", "", "", "", ""},
    {THML_BLOCKQUOTE, "margin-left", "40px", "margin-right", "40px", "", ""},
    {THML_BODY, "margin", "8px", "", "", "", ""},
    {THML_BOOKID, "", "", "", "", "", ""},
    {THML_BR, "", "", "", "", "", ""},
    {THML_BUTTON, "", "", "", "", "", ""},
    {THML_CANVAS, "", "", "", "", "", ""},
    {THML_CAPTION, "text-align", "center", "", "", "", ""},
    {THML_CDATA, "", "", "", "", "", ""},
    {THML_CENTER, "text-align", "center", "", "", "", ""},
    {THML_CHRIST, "", "", "", "", "", ""},
    {THML_CITATION, "", "", "", "", "", ""},
    {THML_CITE, "font-style", "italic", "", "", "", ""},
    {THML_CODE, "font-family", "monospace", "", "", "", ""},
    {THML_COL, "", "", "", "", "", ""},
    {THML_COLGROUP, "", "", "", "", "", ""},
    {THML_COMMAND, "", "", "", "", "", ""},
    {THML_COMMENTS, "", "", "", "", "", ""},
    {THML_COMPOSER, "", "", "", "", "", ""},
    {THML_COPYLOCATION, "", "", "", "", "", ""},
    {THML_DATALIST, "", "", "", "", "", ""},
    {THML_DATE, "", "", "", "", "", ""},
    {THML_DC, "", "", "", "", "", ""},
    {THML_DC_CONTRIBUTOR, "", "", "", "", "", ""},
    {THML_DC_COVERAGE, "", "", "", "", "", ""},
    {THML_DC_CREATOR, "", "", "", "", "", ""},
    {THML_DC_DATE, "", "", "", "", "", ""},
    {THML_DC_DESCRIPTION, "", "", "", "", "", ""},
    {THML_DC_FORMAT, "", "", "", "", "", ""},
    {THML_DC_IDENTIFIER, "", "", "", "", "", ""},
    {THML_DC_LANGUAGE, "", "", "", "", "", ""},
    {THML_DC_PUBLISHER, "", "", "", "", "", ""},
    {THML_DC_RELATION, "", "", "", "", "", ""},
    {THML_DC_RIGHTS, "", "", "", "", "", ""},
    {THML_DC_SOURCE, "", "", "", "", "", ""},
    {THML_DC_SUBJECT, "", "", "", "", "", ""},
    {THML_DC_TITLE, "", "", "", "", "", ""},
    {THML_DC_TYPE, "", "", "", "", "", ""},
    {THML_DD, "margin-left", "40px", "", "", "", ""},
    {THML_DEF, "", "", "", "", "", ""},
    {THML_DEL, "text-decoration", "line-through", "", "", "", ""},
    {THML_DELETED, "", "", "", "", "", ""},
    {THML_DESCRIPTION, "", "", "", "", "", ""},
    {THML_DETAILS, "", "", "", "", "", ""},
    {THML_DFN, "font-style", "italic", "", "", "", ""},
    {THML_DIALOG, "", "", "", "", "", ""},
    {THML_DIR, "margin-left", "40px", "", "", "", ""},
    {THML_DIV, "", "", "", "", "", ""},
    {THML_DIV1, "", "", "", "", "", ""},
    {THML_DIV2, "", "", "", "", "", ""},
    {THML_DIV3, "", "", "", "", "", ""},
    {THML_DIV4, "", "", "", "", "", ""},
    {THML_DIV5, "", "", "", "", "", ""},
    {THML_DIV6, "", "", "", "", "", ""},
    {THML_DL, "margin", "1.12em 0", "", "", "", ""},
    {THML_DT, "", "", "", "", "", ""},
    {THML_EDITORIALCOMMENTS, "", "", "", "", "", ""},
    {THML_ELECTRONICEDINFO, "", "", "", "", "", ""},
    {THML_ELEMENT, "", "", "", "", "", ""},
    {THML_EM, "font-style", "italic", "", "", "", ""},
    {THML_EMBED, "", "", "", "", "", ""},
    {THML_ENTITY, "", "", "", "", "", ""},
    {THML_FIELDSET, "margin", "1.12em 0", "", "", "", ""},
    {THML_FIGCAPTION, "", "", "", "", "", ""},
    {THML_FIGURE, "", "", "", "", "", ""},
    {THML_FILE, "", "", "", "", "", ""},
    {THML_FIRSTPUBLISHED, "", "", "", "", "", ""},
    {THML_FONT, "", "", "", "", "", ""},
    {THML_FOOTER, "", "", "", "", "", ""},
    {THML_FOREIGN, "", "", "", "", "", ""},
    {THML_FORM, "margin", "1.12em 0", "", "", "", ""},
    {THML_FRAME, "", "", "", "", "", ""},
    {THML_FRAMESET, "", "", "", "", "", ""},
    {THML_GENERALINFO, "", "", "", "", "", ""},
    {THML_GLOSSARY, "", "", "", "", "", ""},
    {THML_GLOSSARY_ITEM, "", "", "", "", "", ""},
    {THML_HEAD, "", "", "", "", "", ""},
    {THML_HEADER, "", "", "", "", "", ""},
    {THML_HR, "text-align", "center", "width", "100%", "", ""},
    {THML_HTML, "", "", "", "", "", ""},
    {THML_HYMN, "", "", "", "", "", ""},
    {THML_H1, "font-size", "2em", "margin", ".67em 0", "font-weight", "bolder"},
    {THML_H2, "font-size", "1.5em", "margin", ".75em 0", "font-weight", "bolder"},
    {THML_H3, "font-size", "1.17em", "margin", ".83em 0", "font-weight", "bolder"},
    {THML_H4, "margin", "1.12em 0", "font-weight", "bolder", "", ""},
    {THML_H5, "font-size", ".83em", "margin", "1.5em 0", "font-weight", "bolder"},
    {THML_H6, "font-size", ".75em", "margin", "1.67em 0", "font-weight", "bolder"},
    {THML_I, "font-style", "italic", "", "", "", ""},
    {THML_IFRAME, "", "", "", "", "", ""},
    {THML_IMAGE, "", "", "", "", "", ""},
    {THML_IMG, "", "", "", "", "", ""},
    {THML_INCIPIT, "", "", "", "", "", ""},
    {THML_INDEX, "", "", "", "", "", ""},
    {THML_INPUT, "", "", "", "", "", ""},
    {THML_INS, "text-decoration", "underline", "", "", "", ""},
    {THML_INSERTINDEX, "", "", "", "", "", ""},
    {THML_INTERFACE, "", "", "", "", "", ""},
    {THML_KBD, "font-family", "monospace", "", "", "", ""},
    {THML_KEYGEN, "", "", "", "", "", ""},
    {THML_L, "", "", "", "", "", ""},
    {THML_LABEL, "", "", "", "", "", ""},
    {THML_LEGEND, "", "", "", "", "", ""},
    {THML_LI, "", "", "", "", "", ""},
    {THML_LINK, "", "", "", "", "", ""},
    {THML_MAP, "", "", "", "", "", ""},
    {THML_MARK, "background-color", "yellow", "", "", "", ""},
    {THML_MENU, "margin-left", "40px", "", "", "", ""},
    {THML_META, "", "", "", "", "", ""},
    {THML_METER, "", "", "", "", "", ""},
    {THML_MODULE, "", "", "", "", "", ""},
    {THML_MUSIC, "", "", "", "", "", ""},
    {THML_NAME, "", "", "", "", "", ""},
    {THML_NAV, "", "", "", "", "", ""},
    {THML_NOFRAMES, "", "", "", "", "", ""},
    {THML_NOSCRIPT, "", "", "", "", "", ""},
    {THML_NOTE, "", "", "", "", "", ""},
    {THML_OBJECT, "", "", "", "", "", ""},
    {THML_OL, "margin-left", "40px", "list-style-type", "decimal", "", ""},
    {THML_OPTGROUP, "", "", "", "", "", ""},
    {THML_OPTION, "", "", "", "", "", ""},
    {THML_OUTPUT, "", "", "", "", "", ""},
    {THML_P, "margin", "1.12em 0", "", "", "", ""},
    {THML_PARAM, "", "", "", "", "", ""},
    {THML_PB, "", "", "", "", "", ""},
    {THML_PRE, "font-family", "monospace", "white-space", "pre", "", ""},
    {THML_PRINTSOURCEINFO, "", "", "", "", "", ""},
    {THML_PROGRESS, "", "", "", "", "", ""},
    {THML_PROPERTY, "", "", "", "", "", ""},
    {THML_PUBHISTORY, "", "", "", "", "", ""},
    {THML_PUBLISHED, "", "", "", "", "", ""},
    {THML_PUBLISHERID, "", "", "", "", "", ""},
    {THML_Q, "", "", "", "", "", ""},
    {THML_REVISIONHISTORY, "", "", "", "", "", ""},
    {THML_RP, "", "", "", "", "", ""},
    {THML_RT, "", "", "", "", "", ""},
    {THML_RUBY, "", "", "", "", "", ""},
    {THML_S, "text-decoration", "line-through", "", "", "", ""},
    {THML_SAMP, "font-family", "monospace", "", "", "", ""},
    {THML_SCRIPCOM, "", "", "", "", "", ""},
    {THML_SCRIPCONTEXT, "", "", "", "", "", ""},
    {THML_SCRIPREF, "", "", "", "", "", ""},
    {THML_SCRIPT, "", "", "", "", "", ""},
    {THML_SCRIPTURE, "", "", "", "", "", ""},
    {THML_SECTION, "", "", "", "", "", ""},
    {THML_SELECT, "", "", "", "", "", ""},
    {THML_SELECTOR, "", "", "", "", "", ""},
    {THML_SERIES, "", "", "", "", "", ""},
    {THML_SMALL, "font-size", ".83em", "", "", "", ""},
    {THML_SOURCE, "", "", "", "", "", ""},
    {THML_SPAN, "", "", "", "", "", ""},
    {THML_STATUS, "", "", "", "", "", ""},
    {THML_STRIKE, "text-decoration", "line-through", "", "", "", ""},
    {THML_STRONG, "font-weight", "bolder", "", "", "", ""},
    {THML_STYLE, "", "", "", "", "", ""},
    {THML_SUB, "font-size", ".90em", "vertical-align", "sub", "", ""},
    {THML_SUMMARY, "", "", "", "", "", ""},
    {THML_SUP, "font-size", ".90em", "vertical-align", "super", "", ""},
    {THML_SYNC, "", "", "", "", "", ""},
    {THML_TABLE, "border-spacing", "2px", "border-width", "1px", "border-style", "solid"},
    {THML_TBODY, "vertical-align", "middle", "", "", "", ""},
    {THML_TD, "vertical-align", "inherit", "", "", "", ""},
    {THML_TERM, "", "", "", "", "", ""},
    {THML_TERM_STRONGS, "", "", "", "", "", ""},
    {THML_TEXTAREA, "", "", "", "", "", ""},
    {THML_TFOOT, "vertical-align", "middle", "", "", "", ""},
    {THML_TH, "font-weight", "bolder", "text-align", "center", "vertical-align", "inherit"},
    {THML_THEAD, "vertical-align", "middle", "", "", "", ""},
    {THML_THML, "", "", "", "", "", ""},
    {THML_THML_BODY, "", "", "", "", "", ""},
    {THML_THML_HEAD, "", "", "", "", "", ""},
    {THML_TIME, "", "", "", "", "", ""},
    {THML_TITLE, "", "", "", "", "", ""},
    {THML_TR, "", "", "", "", "", ""},
    {THML_TRACK, "", "", "", "", "", ""},
    {THML_TT, "font-family", "monospace", "", "", "", ""},
    {THML_TUNE, "", "", "", "", "", ""},
    {THML_U, "text-decoration", "underline", "", "", "", ""},
    {THML_UL, "margin-left", "40px", "", "", "", ""},
    {THML_UNCLEAR, "", "", "", "", "", ""},
    {THML_VAR, "font-style", "italic", "", "", "", ""},
    {THML_VERSE, "", "", "", "", "", ""},
    {THML_VERSION, "", "", "", "", "", ""},
    {THML_VIDEO, "", "", "", "", "", ""},
    {THML_WBR, "", "", "", "", "", ""},
    {THML_XML, "", "", "", "", "", ""},
    {THML_XML_STYLESHEET, "", "", "", "", "", ""}
};

void SwHtmlCss::GetElementStyle(swUI16 element, CssAttributeList & styleList)
{
    if (element >= N_THML_ELEMENTS)
        return;

    if (htmlCss[element].m_attribute1[0] != '\0' && htmlCss[element].m_value1[0] != '\0')
    {
        styleList.Add(htmlCss[element].m_attribute1, htmlCss[element].m_value1, 1);
    }

    if (htmlCss[element].m_attribute2[0] != '\0' && htmlCss[element].m_value2[0] != '\0')
    {
        styleList.Add(htmlCss[element].m_attribute2, htmlCss[element].m_value2, 1);
    }

    if (htmlCss[element].m_attribute3[0] != '\0' && htmlCss[element].m_value3[0] != '\0')
    {
        styleList.Add(htmlCss[element].m_attribute3, htmlCss[element].m_value3, 1);
    }
}
