///////////////////////////////////////////////////////////////////
// Name:        binding.cpp
// Purpose:     Bind/Unbind events generated by wxRichTextCtrl
//              to/from this control.
// Copyright:   David Reynolds
// License:     Sower Applications License
///////////////////////////////////////////////////////////////////

#include "../../include/richtext/richtextctrlext.h"

void SwRichTextCtrl::BindCtrl()
{
    Bind(wxEVT_RICHTEXT_LEFT_CLICK, &SwRichTextCtrl::OnThisRichTextLeftClick, this);
    Bind(wxEVT_RICHTEXT_RIGHT_CLICK, &SwRichTextCtrl::OnThisRichTextRightClick, this);
    Bind(wxEVT_RICHTEXT_MIDDLE_CLICK, &SwRichTextCtrl::OnThisRichTextMiddleClick, this);
    Bind(wxEVT_RICHTEXT_LEFT_DCLICK, &SwRichTextCtrl::OnThisRichTextLeftDClick, this);
    Bind(wxEVT_RICHTEXT_RETURN, &SwRichTextCtrl::OnThisRichTextReturn, this);
    Bind(wxEVT_RICHTEXT_CHARACTER, &SwRichTextCtrl::OnThisRichTextCharacter, this);
    Bind(wxEVT_RICHTEXT_DELETE, &SwRichTextCtrl::OnThisRichTextDelete, this);
    Bind(wxEVT_RICHTEXT_SELECTION_CHANGED, &SwRichTextCtrl::OnThisRichTextSelectionChanged, this);
    Bind(wxEVT_RICHTEXT_FOCUS_OBJECT_CHANGED, &SwRichTextCtrl::OnThisRichTextFocusObjectChanged, this);
    Bind(wxEVT_TEXT, &SwRichTextCtrl::OnThisRichTextText, this);
    Bind(wxEVT_TEXT_ENTER, &SwRichTextCtrl::OnThisRichTextTextEnter, this);
    Bind(wxEVT_TEXT_URL, &SwRichTextCtrl::OnThisRichTextUrl, this);
    Bind(wxEVT_SCROLLWIN_LINEUP, &SwRichTextCtrl::OnScrollWin, this);
    Bind(wxEVT_SCROLLWIN_LINEDOWN, &SwRichTextCtrl::OnScrollWin, this);
    Bind(wxEVT_SCROLLWIN_TOP, &SwRichTextCtrl::OnScrollWin, this);
    Bind(wxEVT_SCROLLWIN_BOTTOM, &SwRichTextCtrl::OnScrollWin, this);
    Bind(wxEVT_SCROLLWIN_THUMBTRACK, &SwRichTextCtrl::OnScrollWin, this);
    Bind(wxEVT_SCROLLWIN_THUMBRELEASE, &SwRichTextCtrl::OnScrollWin, this);
    Bind(wxEVT_SCROLLWIN_PAGEUP, &SwRichTextCtrl::OnScrollWin, this);
    Bind(wxEVT_SCROLLWIN_PAGEDOWN, &SwRichTextCtrl::OnScrollWin, this);
    Bind(wxEVT_SIZE, &SwRichTextCtrl::OnSizeWin, this);
}

void SwRichTextCtrl::UnbindCtrl()
{
    Unbind(wxEVT_RICHTEXT_LEFT_CLICK, &SwRichTextCtrl::OnThisRichTextLeftClick, this);
    Unbind(wxEVT_RICHTEXT_RIGHT_CLICK, &SwRichTextCtrl::OnThisRichTextRightClick, this);
    Unbind(wxEVT_RICHTEXT_MIDDLE_CLICK, &SwRichTextCtrl::OnThisRichTextMiddleClick, this);
    Unbind(wxEVT_RICHTEXT_LEFT_DCLICK, &SwRichTextCtrl::OnThisRichTextLeftDClick, this);
    Unbind(wxEVT_RICHTEXT_RETURN, &SwRichTextCtrl::OnThisRichTextReturn, this);
    Unbind(wxEVT_RICHTEXT_CHARACTER, &SwRichTextCtrl::OnThisRichTextCharacter, this);
    Unbind(wxEVT_RICHTEXT_DELETE, &SwRichTextCtrl::OnThisRichTextDelete, this);
    Unbind(wxEVT_RICHTEXT_SELECTION_CHANGED, &SwRichTextCtrl::OnThisRichTextSelectionChanged, this);
    Unbind(wxEVT_RICHTEXT_FOCUS_OBJECT_CHANGED, &SwRichTextCtrl::OnThisRichTextFocusObjectChanged, this);
    Unbind(wxEVT_TEXT, &SwRichTextCtrl::OnThisRichTextText, this);
    Unbind(wxEVT_TEXT_ENTER, &SwRichTextCtrl::OnThisRichTextTextEnter, this);
    Unbind(wxEVT_TEXT_URL, &SwRichTextCtrl::OnThisRichTextUrl, this);
    Unbind(wxEVT_SCROLLWIN_LINEUP, &SwRichTextCtrl::OnScrollWin, this);
    Unbind(wxEVT_SCROLLWIN_LINEDOWN, &SwRichTextCtrl::OnScrollWin, this);
    Unbind(wxEVT_SCROLLWIN_TOP, &SwRichTextCtrl::OnScrollWin, this);
    Unbind(wxEVT_SCROLLWIN_BOTTOM, &SwRichTextCtrl::OnScrollWin, this);
    Unbind(wxEVT_SCROLLWIN_THUMBTRACK, &SwRichTextCtrl::OnScrollWin, this);
    Unbind(wxEVT_SCROLLWIN_THUMBRELEASE, &SwRichTextCtrl::OnScrollWin, this);
    Unbind(wxEVT_SCROLLWIN_PAGEUP, &SwRichTextCtrl::OnScrollWin, this);
    Unbind(wxEVT_SCROLLWIN_PAGEDOWN, &SwRichTextCtrl::OnScrollWin, this);
    Unbind(wxEVT_SIZE, &SwRichTextCtrl::OnSizeWin, this);
}
