///////////////////////////////////////////////////////////////////
// Name:        url.cpp
// Purpose:     Handle url events generated by wxRichTextCtrl.
// Copyright:   David Reynolds
// License:     Sower Applications License
///////////////////////////////////////////////////////////////////

#include "../../include/richtext/richtextctrlext.h"
#include "../../include/appi/appifa.h"

void SwRichTextCtrl::OnThisRichTextUrl(wxTextUrlEvent& event)
{
    wxRichTextAttr attr;
    wxRichTextRange range;
    range.SetRange(event.GetURLStart(), event.GetURLEnd() + 1);
    wxString url;
    swUI32 pos;

    if (GetStyleForRange(range, attr))
    {
        url = attr.GetURL();
        if (url.Find("anchor:") == 0)
        {
            url.Remove(0, 7);

            pos = m_anchor.Find(url.utf8_str());
            if (pos != NODE_ID_INVALID)
            {
                JumpToAnchorPosition(pos);
            }
        }
        else if (url.Find("note:") == 0)
        {
            url.Remove(0, 5);
            pos = m_anchor.Find(url.utf8_str());
            if (pos != NODE_ID_INVALID)
            {
                JumpToAnchorPosition(pos);
            }
        }
        else if (url.Find("rtx:anchor:") == 0)
        {
            url.Remove(0, 11);
            pos = m_anchor.Find(url.utf8_str());
            if (pos != NODE_ID_INVALID)
            {
                JumpToAnchorPosition(url);
            }
        }
        else if (url.Find("audio:") == 0)
        {
            url.Remove(0, 6);
            SwApplicationInterface::GetAudio().Open(url.utf8_str());
            SwApplicationInterface::GetAudio().Play();
        }
        else if (url.Find("media:") == 0)
        {
            url.Remove(0, 6);
            // For future use.
        }
        else
        {
            // Links, scripture: & module: etc. passed to derived
            // classes.
            OnUrlClick(url, m_adClientPos.y - 1, m_adClientPos.y + (m_adCaret.GetHeight() + 1));
        }
    }

    m_lastmousePos = m_adClientPos;
    m_urlClicked = true;
    event.Skip();
}
